### PR TITLE
add email notifications from ocfkanboard@ocf.berkeley.edu

### LINKED ISSUE #2: Configure SMTP for email notifications

### PR DESCRIPTION
**Pull request by cg505**
resolves #2

### CODE REVIEW

**Comment by dkess** [comment]
Does this work? I would be surprised if it did, since you shouldn't need to enable encryption on SMTP port 25.

**Comment by cg505** [comment]
It is tested and works. Why would we disable encryption?

**Comment by dkess** [comment]
We don't need to encrypt traffic within our own network, which is all that does.

**Review by abizer — APPROVED** [review]
lgtm, encrypting inside the network is probably fine and we can disable it if we need to debug something

**Comment by dkess** [comment]
yeah it's fine, I just though 25 didn't support encryption but ｉｆ ｉｔ ｗｏｒｋｓ ｉｔ ｗｏｒｋｓ

**Review by dkess — APPROVED** [review]

**Comment by abizer** [comment]
get you some of that ｓｔａｒｔｔｌｓ

**Pull request merged**
